/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: RM02 (https://sketchfab.com/RM02)
License: https://help.3dexport.com/item/basic-and-extended-license-usage-examples/
Source: https://sketchfab.com/3d-models/maersk-container-ship-8c39021a0dc44ca6b6ca611cc967e540
Title: Maersk Container Ship
*/

import { useGLTF } from "@react-three/drei";

export default function Boat(props) {
  const { nodes, materials } = useGLTF("/maersk_container_ship_light.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group
          position={[585.693, 633.404, 388.893]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
          scale={100}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ship_Bridge_0.geometry}
            material={materials.Bridge}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ship_Bridge_0_1.geometry}
            material={materials.Bridge}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ship_Hull_0.geometry}
            material={materials.Hull}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Ship_Hull_0_1.geometry}
            material={materials.Hull}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Containers_Containers_0.geometry}
          material={materials.Containers}
          position={[-47.17, 475.961, -412.06]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={102.184}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/maersk_container_ship_light.glb");
